// Generated by gencpp from file xarm6_demo/MoveResult.msg
// DO NOT EDIT!


#ifndef XARM6_DEMO_MESSAGE_MOVERESULT_H
#define XARM6_DEMO_MESSAGE_MOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm6_demo
{
template <class ContainerAllocator>
struct MoveResult_
{
  typedef MoveResult_<ContainerAllocator> Type;

  MoveResult_()
    : success(false)
    , err_code(0)  {
    }
  MoveResult_(const ContainerAllocator& _alloc)
    : success(false)
    , err_code(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int16_t _err_code_type;
  _err_code_type err_code;





  typedef boost::shared_ptr< ::xarm6_demo::MoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm6_demo::MoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResult_

typedef ::xarm6_demo::MoveResult_<std::allocator<void> > MoveResult;

typedef boost::shared_ptr< ::xarm6_demo::MoveResult > MoveResultPtr;
typedef boost::shared_ptr< ::xarm6_demo::MoveResult const> MoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm6_demo::MoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm6_demo::MoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xarm6_demo::MoveResult_<ContainerAllocator1> & lhs, const ::xarm6_demo::MoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.err_code == rhs.err_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xarm6_demo::MoveResult_<ContainerAllocator1> & lhs, const ::xarm6_demo::MoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xarm6_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::xarm6_demo::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm6_demo::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm6_demo::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm6_demo::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm6_demo::MoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm6_demo::MoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm6_demo::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd37d58cd262d8243347be50af0c1a3f";
  }

  static const char* value(const ::xarm6_demo::MoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd37d58cd262d824ULL;
  static const uint64_t static_value2 = 0x3347be50af0c1a3fULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm6_demo::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm6_demo/MoveResult";
  }

  static const char* value(const ::xarm6_demo::MoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm6_demo::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"bool success \n"
"\n"
"int16 err_code\n"
"\n"
;
  }

  static const char* value(const ::xarm6_demo::MoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm6_demo::MoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.err_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm6_demo::MoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm6_demo::MoveResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "err_code: ";
    Printer<int16_t>::stream(s, indent + "  ", v.err_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM6_DEMO_MESSAGE_MOVERESULT_H
