// Generated by gencpp from file learn_action/TurtleMoveResult.msg
// DO NOT EDIT!


#ifndef LEARN_ACTION_MESSAGE_TURTLEMOVERESULT_H
#define LEARN_ACTION_MESSAGE_TURTLEMOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learn_action
{
template <class ContainerAllocator>
struct TurtleMoveResult_
{
  typedef TurtleMoveResult_<ContainerAllocator> Type;

  TurtleMoveResult_()
    : turtle_final_x(0.0)
    , turtle_final_y(0.0)
    , turtle_final_theta(0.0)  {
    }
  TurtleMoveResult_(const ContainerAllocator& _alloc)
    : turtle_final_x(0.0)
    , turtle_final_y(0.0)
    , turtle_final_theta(0.0)  {
  (void)_alloc;
    }



   typedef double _turtle_final_x_type;
  _turtle_final_x_type turtle_final_x;

   typedef double _turtle_final_y_type;
  _turtle_final_y_type turtle_final_y;

   typedef double _turtle_final_theta_type;
  _turtle_final_theta_type turtle_final_theta;





  typedef boost::shared_ptr< ::learn_action::TurtleMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_action::TurtleMoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleMoveResult_

typedef ::learn_action::TurtleMoveResult_<std::allocator<void> > TurtleMoveResult;

typedef boost::shared_ptr< ::learn_action::TurtleMoveResult > TurtleMoveResultPtr;
typedef boost::shared_ptr< ::learn_action::TurtleMoveResult const> TurtleMoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_action::TurtleMoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_action::TurtleMoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learn_action::TurtleMoveResult_<ContainerAllocator1> & lhs, const ::learn_action::TurtleMoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.turtle_final_x == rhs.turtle_final_x &&
    lhs.turtle_final_y == rhs.turtle_final_y &&
    lhs.turtle_final_theta == rhs.turtle_final_theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learn_action::TurtleMoveResult_<ContainerAllocator1> & lhs, const ::learn_action::TurtleMoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learn_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_action::TurtleMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_action::TurtleMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_action::TurtleMoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e7b4195ae4864a401f0242e01596152";
  }

  static const char* value(const ::learn_action::TurtleMoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e7b4195ae4864a4ULL;
  static const uint64_t static_value2 = 0x01f0242e01596152ULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_action/TurtleMoveResult";
  }

  static const char* value(const ::learn_action::TurtleMoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"float64 turtle_final_x\n"
"float64 turtle_final_y\n"
"float64 turtle_final_theta\n"
;
  }

  static const char* value(const ::learn_action::TurtleMoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtle_final_x);
      stream.next(m.turtle_final_y);
      stream.next(m.turtle_final_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleMoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_action::TurtleMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_action::TurtleMoveResult_<ContainerAllocator>& v)
  {
    s << indent << "turtle_final_x: ";
    Printer<double>::stream(s, indent + "  ", v.turtle_final_x);
    s << indent << "turtle_final_y: ";
    Printer<double>::stream(s, indent + "  ", v.turtle_final_y);
    s << indent << "turtle_final_theta: ";
    Printer<double>::stream(s, indent + "  ", v.turtle_final_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_ACTION_MESSAGE_TURTLEMOVERESULT_H
