// Generated by gencpp from file visp_camera_calibration/CalibPointArray.msg
// DO NOT EDIT!


#ifndef VISP_CAMERA_CALIBRATION_MESSAGE_CALIBPOINTARRAY_H
#define VISP_CAMERA_CALIBRATION_MESSAGE_CALIBPOINTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <visp_camera_calibration/CalibPoint.h>

namespace visp_camera_calibration
{
template <class ContainerAllocator>
struct CalibPointArray_
{
  typedef CalibPointArray_<ContainerAllocator> Type;

  CalibPointArray_()
    : points()  {
    }
  CalibPointArray_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::visp_camera_calibration::CalibPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::visp_camera_calibration::CalibPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> const> ConstPtr;

}; // struct CalibPointArray_

typedef ::visp_camera_calibration::CalibPointArray_<std::allocator<void> > CalibPointArray;

typedef boost::shared_ptr< ::visp_camera_calibration::CalibPointArray > CalibPointArrayPtr;
typedef boost::shared_ptr< ::visp_camera_calibration::CalibPointArray const> CalibPointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator1> & lhs, const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator1> & lhs, const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visp_camera_calibration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46e7b53381d96d2d7cbbb7418f6dd696";
  }

  static const char* value(const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46e7b53381d96d2dULL;
  static const uint64_t static_value2 = 0x7cbbb7418f6dd696ULL;
};

template<class ContainerAllocator>
struct DataType< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visp_camera_calibration/CalibPointArray";
  }

  static const char* value(const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# an array of vpPoint\n"
"visp_camera_calibration/CalibPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: visp_camera_calibration/CalibPoint\n"
"# a vpPoint\n"
"\n"
"int32 i\n"
"int32 j\n"
"float64 X\n"
"float64 Y\n"
"float64 Z\n"
"\n"
;
  }

  static const char* value(const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibPointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visp_camera_calibration::CalibPointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visp_camera_calibration::CalibPointArray_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::visp_camera_calibration::CalibPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISP_CAMERA_CALIBRATION_MESSAGE_CALIBPOINTARRAY_H
