// Auto-generated. Do not edit!

// (in-package learn_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TurtleMoveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.turtle_target_x = null;
      this.turtle_target_y = null;
      this.turtle_target_theta = null;
    }
    else {
      if (initObj.hasOwnProperty('turtle_target_x')) {
        this.turtle_target_x = initObj.turtle_target_x
      }
      else {
        this.turtle_target_x = 0.0;
      }
      if (initObj.hasOwnProperty('turtle_target_y')) {
        this.turtle_target_y = initObj.turtle_target_y
      }
      else {
        this.turtle_target_y = 0.0;
      }
      if (initObj.hasOwnProperty('turtle_target_theta')) {
        this.turtle_target_theta = initObj.turtle_target_theta
      }
      else {
        this.turtle_target_theta = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TurtleMoveGoal
    // Serialize message field [turtle_target_x]
    bufferOffset = _serializer.float64(obj.turtle_target_x, buffer, bufferOffset);
    // Serialize message field [turtle_target_y]
    bufferOffset = _serializer.float64(obj.turtle_target_y, buffer, bufferOffset);
    // Serialize message field [turtle_target_theta]
    bufferOffset = _serializer.float64(obj.turtle_target_theta, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TurtleMoveGoal
    let len;
    let data = new TurtleMoveGoal(null);
    // Deserialize message field [turtle_target_x]
    data.turtle_target_x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [turtle_target_y]
    data.turtle_target_y = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [turtle_target_theta]
    data.turtle_target_theta = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learn_action/TurtleMoveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd6ca75a13b0855b8f735f0fec295b281';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    float64 turtle_target_x  # Specify Turtle's　target position
    float64 turtle_target_y
    float64 turtle_target_theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TurtleMoveGoal(null);
    if (msg.turtle_target_x !== undefined) {
      resolved.turtle_target_x = msg.turtle_target_x;
    }
    else {
      resolved.turtle_target_x = 0.0
    }

    if (msg.turtle_target_y !== undefined) {
      resolved.turtle_target_y = msg.turtle_target_y;
    }
    else {
      resolved.turtle_target_y = 0.0
    }

    if (msg.turtle_target_theta !== undefined) {
      resolved.turtle_target_theta = msg.turtle_target_theta;
    }
    else {
      resolved.turtle_target_theta = 0.0
    }

    return resolved;
    }
};

module.exports = TurtleMoveGoal;
