// Auto-generated. Do not edit!

// (in-package learn_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TurtleMoveResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.turtle_final_x = null;
      this.turtle_final_y = null;
      this.turtle_final_theta = null;
    }
    else {
      if (initObj.hasOwnProperty('turtle_final_x')) {
        this.turtle_final_x = initObj.turtle_final_x
      }
      else {
        this.turtle_final_x = 0.0;
      }
      if (initObj.hasOwnProperty('turtle_final_y')) {
        this.turtle_final_y = initObj.turtle_final_y
      }
      else {
        this.turtle_final_y = 0.0;
      }
      if (initObj.hasOwnProperty('turtle_final_theta')) {
        this.turtle_final_theta = initObj.turtle_final_theta
      }
      else {
        this.turtle_final_theta = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TurtleMoveResult
    // Serialize message field [turtle_final_x]
    bufferOffset = _serializer.float64(obj.turtle_final_x, buffer, bufferOffset);
    // Serialize message field [turtle_final_y]
    bufferOffset = _serializer.float64(obj.turtle_final_y, buffer, bufferOffset);
    // Serialize message field [turtle_final_theta]
    bufferOffset = _serializer.float64(obj.turtle_final_theta, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TurtleMoveResult
    let len;
    let data = new TurtleMoveResult(null);
    // Deserialize message field [turtle_final_x]
    data.turtle_final_x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [turtle_final_y]
    data.turtle_final_y = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [turtle_final_theta]
    data.turtle_final_theta = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'learn_action/TurtleMoveResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0e7b4195ae4864a401f0242e01596152';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    float64 turtle_final_x
    float64 turtle_final_y
    float64 turtle_final_theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TurtleMoveResult(null);
    if (msg.turtle_final_x !== undefined) {
      resolved.turtle_final_x = msg.turtle_final_x;
    }
    else {
      resolved.turtle_final_x = 0.0
    }

    if (msg.turtle_final_y !== undefined) {
      resolved.turtle_final_y = msg.turtle_final_y;
    }
    else {
      resolved.turtle_final_y = 0.0
    }

    if (msg.turtle_final_theta !== undefined) {
      resolved.turtle_final_theta = msg.turtle_final_theta;
    }
    else {
      resolved.turtle_final_theta = 0.0
    }

    return resolved;
    }
};

module.exports = TurtleMoveResult;
